version: "3.7"

services:
  predictor:
    image: cerco/predictor:latest
    volumes:
      - "./app:/app/predictor"
    working_dir: /app/predictor
    entrypoint: ["Rscript", "script.R", "5"]
    stdin_open: true
